/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/**
 * Instanciates the internal PNG decoder.<br>
 */
#ifndef _LLDISPLAY_DECODER_PNG
#define _LLDISPLAY_DECODER_PNG 
#include <intern/LLDISPLAY_DECODER_PNG.h>
#include <stdint.h>
#include <LLDISPLAY_DECODER.h>
#ifdef __cplusplus
	extern "C" {
#endif
// --------------------------------------------------------------------------------
// -                      Functions provided by the platform                      -
// --------------------------------------------------------------------------------

/**
 * Instanciates the internal PNG decoder.
 * @return the PNG decoder instance
 */
LLDISPLAY_DECODER* LLDISPLAY_DECODER_PNG_createPNGImageDecoder(void);

#ifdef __cplusplus
	}
#endif
#endif
