/* 
 * IceTea
 * 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/**
 * Type of display stack's image decoder 
 */
#ifndef _LLDISPLAY_DECODER
#define _LLDISPLAY_DECODER 
#include <intern/LLDISPLAY_DECODER.h>
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#ifdef __cplusplus
	}
#endif
#endif
