/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * Implementation header file. Shall only be included by client implementation C files.
 */
#include <LLINPUT_LISTENER_STATES.h>
#include <stdint.h>
#include <intern/LLINPUT_LISTENER_STATES_impl.h>
#include <LLINPUT_DEVICE.h>
// --------------------------------------------------------------------------------
// -                      Functions that must be implemented                      -
// --------------------------------------------------------------------------------

/**
 * A STATE action has occurred on the given state machine.
 * @param states the group state machines
 * @param stateID the ID of the state machine in the state machine group
 * @param stateValue the new state machine value
 * @return 1 if the state action has been managed by the listener
 */
uint8_t LLINPUT_LISTENER_STATES_IMPL_stateChanged(LLINPUT_DEVICE* states, int32_t stateID, int32_t stateValue);
