/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * Implementation header file. Shall only be included by client implementation C files.
 */
#include <LLINPUT_DEVICE.h>
#include <stdint.h>
#include <intern/LLINPUT_DEVICE_impl.h>
#ifndef LLINPUT_DEVICE_IMPL
#warning "Implementation tag has not been defined. Default implementation tag is LLINPUT_DEVICE_IMPL"
#endif
