/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * Implementation header file. Shall only be included by client implementation C files.
 */
#include <LLINPUT_LISTENER_GENERICDEVICE.h>
#include <stdint.h>
#include <intern/LLINPUT_LISTENER_GENERICDEVICE_impl.h>
#include <LLINPUT_DEVICE.h>
// --------------------------------------------------------------------------------
// -                      Functions that must be implemented                      -
// --------------------------------------------------------------------------------

/**
 * An event has occurred on the given device.
 * @param input the device instance
 * @param event the device event
 * @return 1 if the event has been managed by the listener
 */
uint8_t LLINPUT_LISTENER_GENERICDEVICE_IMPL_eventReceived(LLINPUT_DEVICE* input, int32_t event);
