/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/**
 * Represents a hardware device (pointer, group of buttons etc.)
 */
#ifndef _LLINPUT_DEVICE
#define _LLINPUT_DEVICE 
#include <intern/LLINPUT_DEVICE.h>
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
// --------------------------------------------------------------------------------
// -                      Functions provided by the platform                      -
// --------------------------------------------------------------------------------

/**
 * Sets an unique ID for this device. The identifier is used to retrieve 
 * the device among the set of inputs with the type.
 * @param uniqueID the unique device ID  
 */
void LLINPUT_DEVICE_setID(LLINPUT_DEVICE* env, int32_t uniqueID);

/**
 * Returns the unique ID
 * @see LLINPUT_DEVICE_setID
 * @return the unique ID
 */
int32_t LLINPUT_DEVICE_getID(LLINPUT_DEVICE* env);

#ifdef __cplusplus
	}
#endif
#endif
