/* 
 * Copyright 2011-2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#include <stdint.h>
#define LLDISPLAY_COPY_CONCAT0(p,s) p ## s
#define LLDISPLAY_COPY_CONCAT(p,s) LLDISPLAY_COPY_CONCAT0(p,s)
#define __icetea__nid__LLDISPLAY_COPY___LLDISPLAY_COPY_IMPL LLDISPLAY_COPY_CONCAT(__icetea__nid__LLDISPLAY_COPY___,LLDISPLAY_COPY_IMPL)
#define LLDISPLAY_COPY_IMPL_new LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_new)
#define LLDISPLAY_COPY_IMPL_initialize LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_initialize)
#define LLDISPLAY_COPY_IMPL_getWidth LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getWidth__Z)
#define LLDISPLAY_COPY_IMPL_getHeight LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getHeight__Z)
#define LLDISPLAY_COPY_IMPL_convertRGBColorToDisplayColor LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_convertRGBColorToDisplayColor__I)
#define LLDISPLAY_COPY_IMPL_convertDisplayColorToRGBColor LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_convertDisplayColorToRGBColor__I)
#define LLDISPLAY_COPY_IMPL_setContrast LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_setContrast__I)
#define LLDISPLAY_COPY_IMPL_getContrast LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getContrast)
#define LLDISPLAY_COPY_IMPL_setBacklight LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_setBacklight__I)
#define LLDISPLAY_COPY_IMPL_hasBackLight LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_hasBackLight)
#define LLDISPLAY_COPY_IMPL_getBacklight LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getBacklight)
#define LLDISPLAY_COPY_IMPL_backlightOn LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_backlightOn)
#define LLDISPLAY_COPY_IMPL_backlightOff LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_backlightOff)
#define LLDISPLAY_COPY_IMPL_getFontAlphaAdjustment LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getFontAlphaAdjustment__I)
#define LLDISPLAY_COPY_IMPL_getWorkingBufferStartAddress LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getWorkingBufferStartAddress)
#define LLDISPLAY_COPY_IMPL_getWorkingBufferEndAddress LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getWorkingBufferEndAddress)
#define LLDISPLAY_COPY_IMPL_isColor LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_isColor)
#define LLDISPLAY_COPY_IMPL_getNumberOfColors LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getNumberOfColors)
#define LLDISPLAY_COPY_IMPL_synchronize LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_synchronize)
#define LLDISPLAY_COPY_IMPL_getBackBufferAddress LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_getBackBufferAddress)
#define LLDISPLAY_COPY_IMPL_copyBuffer LLDISPLAY_COPY_CONCAT(LLDISPLAY_COPY_IMPL,_copyBuffer__IIII)
void __icetea__nid__LLDISPLAY_COPY___LLDISPLAY_COPY_IMPL(void);
void* com_is2t_display_backend_DisplayCopy____4init_5(void* env);

/**
 * Creates a display COPY stack backend driver.
 */
void LLDISPLAY_COPY_IMPL_new(LLDISPLAY_COPY_IMPL* env)
{
	((LLDISPLAY_COPY*)env)->__icetea__id__ = (int32_t)(&__icetea__nid__LLDISPLAY_COPY___LLDISPLAY_COPY_IMPL);
	com_is2t_display_backend_DisplayCopy____4init_5(env);
}
