/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLINPUT_LISTENER_BUTTONS_intern
#define _LLINPUT_LISTENER_BUTTONS_intern 
typedef struct LLINPUT_LISTENER_BUTTONS LLINPUT_LISTENER_BUTTONS;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLINPUT_LISTENER_BUTTONS_buttonPressed __icetea__virtual__com_is2t_inputs_listener_AbstractButtonsListener___buttonPressed__Lcom_is2t_inputs_listener_Device_2I
#define LLINPUT_LISTENER_BUTTONS_buttonReleased __icetea__virtual__com_is2t_inputs_listener_AbstractButtonsListener___buttonReleased__Lcom_is2t_inputs_listener_Device_2I
#define LLINPUT_LISTENER_BUTTONS_buttonRepeated __icetea__virtual__com_is2t_inputs_listener_AbstractButtonsListener___buttonRepeated__Lcom_is2t_inputs_listener_Device_2I
struct LLINPUT_LISTENER_BUTTONS
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
