/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLINPUT_LISTENER_POINTER_intern
#define _LLINPUT_LISTENER_POINTER_intern 
typedef struct LLINPUT_LISTENER_POINTER LLINPUT_LISTENER_POINTER;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLINPUT_LISTENER_POINTER_pointerPressed __icetea__virtual__com_is2t_inputs_listener_AbstractPointerListener___pointerPressed__Lcom_is2t_inputs_listener_Device_2III
#define LLINPUT_LISTENER_POINTER_pointerReleased __icetea__virtual__com_is2t_inputs_listener_AbstractPointerListener___pointerReleased__Lcom_is2t_inputs_listener_Device_2I
#define LLINPUT_LISTENER_POINTER_pointerMoved __icetea__virtual__com_is2t_inputs_listener_AbstractPointerListener___pointerMoved__Lcom_is2t_inputs_listener_Device_2II
struct LLINPUT_LISTENER_POINTER
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
