/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#include <stdint.h>
#define LLINPUT_DEVICE_CONCAT0(p,s) p ## s
#define LLINPUT_DEVICE_CONCAT(p,s) LLINPUT_DEVICE_CONCAT0(p,s)
#define __icetea__nid__LLINPUT_DEVICE___LLINPUT_DEVICE_IMPL LLINPUT_DEVICE_CONCAT(__icetea__nid__LLINPUT_DEVICE___,LLINPUT_DEVICE_IMPL)
#define LLINPUT_DEVICE_IMPL_new LLINPUT_DEVICE_CONCAT(LLINPUT_DEVICE_IMPL,_new)
void __icetea__nid__LLINPUT_DEVICE___LLINPUT_DEVICE_IMPL(void);
void* com_is2t_inputs_listener_Device____4init_5(void* env);

/**
 * Creates an input instance.
 */
void LLINPUT_DEVICE_IMPL_new(LLINPUT_DEVICE_IMPL* env)
{
	((LLINPUT_DEVICE*)env)->__icetea__id__ = (int32_t)(&__icetea__nid__LLINPUT_DEVICE___LLINPUT_DEVICE_IMPL);
	com_is2t_inputs_listener_Device____4init_5(env);
}
