/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLINPUT_DEVICE_intern
#define _LLINPUT_DEVICE_intern 
typedef struct LLINPUT_DEVICE LLINPUT_DEVICE;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLINPUT_DEVICE_setID __icetea__virtual__com_is2t_inputs_listener_Device___setID__I
#define LLINPUT_DEVICE_getID __icetea__virtual__com_is2t_inputs_listener_Device___getID
struct LLINPUT_DEVICE
{
	int32_t __icetea__id__;
	int32_t _reserved0;
};
#ifdef __cplusplus
	}
#endif
#endif
