/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLINPUT_LISTENER_GENERICDEVICE_intern
#define _LLINPUT_LISTENER_GENERICDEVICE_intern 
typedef struct LLINPUT_LISTENER_GENERICDEVICE LLINPUT_LISTENER_GENERICDEVICE;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLINPUT_LISTENER_GENERICDEVICE_eventReceived __icetea__virtual__com_is2t_inputs_listener_AbstractGenericDeviceListener___eventReceived__Lcom_is2t_inputs_listener_Device_2I
struct LLINPUT_LISTENER_GENERICDEVICE
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
