/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
typedef struct LLINPUT LLINPUT;
#include <stdint.h>
#define LLINPUT_CONCAT0(p,s) p ## s
#define LLINPUT_CONCAT(p,s) LLINPUT_CONCAT0(p,s)
#define LLINPUT_IMPL_initialize LLINPUT_CONCAT(LLINPUT_IMPL,_initialize)
#define LLINPUT_IMPL_getInitialStateValue LLINPUT_CONCAT(LLINPUT_IMPL,_getInitialStateValue__II)
#define LLINPUT_IMPL_enterCriticalSection LLINPUT_CONCAT(LLINPUT_IMPL,_enterCriticalSection)
#define LLINPUT_IMPL_leaveCriticalSection LLINPUT_CONCAT(LLINPUT_IMPL,_leaveCriticalSection)
struct LLINPUT
{
	int32_t __icetea__id__;
};
LLINPUT LLINPUT_getSingleton_instance;

/* 
 * Get the unique instance of this type within the system.
 */
LLINPUT* LLINPUT_IMPL_getSingleton(void)
{
	return &LLINPUT_getSingleton_instance;
}
