/* 
 * Copyright 2012-2013 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#include <stdint.h>
#define LLINPUT_LISTENER_GENERICDEVICE_CONCAT0(p,s) p ## s
#define LLINPUT_LISTENER_GENERICDEVICE_CONCAT(p,s) LLINPUT_LISTENER_GENERICDEVICE_CONCAT0(p,s)
#define LLINPUT_LISTENER_GENERICDEVICE_IMPL_eventReceived LLINPUT_LISTENER_GENERICDEVICE_CONCAT(LLINPUT_LISTENER_GENERICDEVICE_IMPL,_eventReceived__Lcom_is2t_inputs_listener_Device_2I)
LLINPUT_LISTENER_GENERICDEVICE LLINPUT_LISTENER_GENERICDEVICE_getSingleton_instance;

/* 
 * Get the unique instance of this type within the system.
 */
LLINPUT_LISTENER_GENERICDEVICE* LLINPUT_LISTENER_GENERICDEVICE_IMPL_getSingleton(void)
{
	return &LLINPUT_LISTENER_GENERICDEVICE_getSingleton_instance;
}
