/* 
 * Copyright 2012 IS2T. All rights reserved.
 * Modification and distribution is permitted under certain conditions.
 * IS2T PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
/* 
 * AUTOGENERATED by COMP-ICETEA-ARMCC-ARM - 1.0.0 - DO NOT EDIT IT
 */
/* 
 * IceTea to C mapping support. Shall not be directly included by clients.
 */
#ifndef _LLMJVM_intern
#define _LLMJVM_intern 
typedef struct LLMJVM LLMJVM;
#include <stdint.h>
#ifdef __cplusplus
	extern "C" {
#endif
#define LLMJVM_initialize __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___initialize
#define LLMJVM_start __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___start__ILiceTea_lang_Ram_2
#define LLMJVM_getExitCode __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___getExitCode
#define LLMJVM_dump __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___dump
#define LLMJVM_getCurrentJavaThreadID __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___getCurrentJavaThreadID
#define LLMJVM_suspendCurrentJavaThread __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___suspendCurrentJavaThread__J
#define LLMJVM_resumeJavaThread __icetea__virtual__com_is2t_microjvm_IGreenThreadMicroJvm___resumeJavaThread__I
struct LLMJVM
{
	int32_t __icetea__id__;
};
#ifdef __cplusplus
	}
#endif
#endif
